### ISSUE TITLE
Data Scope

### ISSUE THREAD

**Issue by pora49494** [pora49494/last-mile-tp#1]
### Row counts
- Data between (2020/1/1 - 2020/7/1), from Japan: **20,148,112**
- We can use more data we just need to write a better query.

### First query plan
- client location: Japan
- server location: Japan
- Date: 2020/1/1 - 2020/7/1
- client AS != server AS

### Additional info 
- m-lab server is on KDDI(2516) and BIGLOBE(2518)

**Comment by pora49494** [comment]
## ToDo 10/7/2020
- [x] median from BQ
- [x] visualization with graph

**Comment by pora49494** [comment]
## ToDo 16/7/2020
- correlation between `TP` and `RTT` (last mile)
- [x] find the median threshold and a nice way to visualize it
   - [x] find median
   - [x] graph
   - data only from 2020

**Comment by pora49494** [comment]
## ToDo 18/7/2020

1. Plot graph for the following period 
    - Period
         - Jan-Feb (as median) 
         - March-May
         - May-Now
    - ASes: Docomo, 9824 => Jcom, 2527 => sonet, 17511 => optage, 2518 => Bigglobe, 18126 => CTC, 17506 => ucom, 2519 => Arteria, 2497 => IIJ.
2. Separate the mobile-IP and the home-IP
    - [softbank1](https://www.support.softbankmobile.co.jp/partner/home_tech1/index.cfm) 
    - [softbank2](https://www.support.softbankmobile.co.jp/partner_st/home_tech1/ios/index.cfm)
    - [au](http://www.au.kddi.com/developer/android/kaihatsu/network/)
    - [au](http://www.au.com/ezfactory/tec/spec/ezsava_ip.html) 
3. Split result for Tokyo and other cities
    - Tokyo VS others
    - Tokyo VS other big cities
    - So that we have a better understanding of where the problem happens
4. Making slide
